stages:
- name: Build Image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: website:prelive
      registry: 127.0.0.1:34070
- name: Deployment
  steps:
  - applyYamlConfig:
      path: ./deployment/deployment.yaml
timeout: 60
notification: {}
