stages:
  - name: Build Image
    steps:
      - publishImageConfig:
          dockerfilePath: ./Dockerfile
          buildContext: .
          tag: app:{CICD_EXECUTION_SEQUENCE}
  - name: Deployment
    steps:
      - applyYamlConfig:
          path: ./deployment/deployment.yaml
timeout: 60
notification: {}
