stages:
  - name: Build Image
    steps:
      - publishImageConfig:
          dockerfilePath: ./Dockerfile
          buildContext: .
          tag: mywebsite:latest
  - name: Deployment
    steps:
      - applyYamlConfig:
          path: ./deployment/deployment.yaml
timeout: 60
notification: {}
