apiVersion: v1
kind: Service
metadata:
  name: website-prelive
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30000
  selector:
    app: website-prelive
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
spec:
  selector:
    matchLabels:
      app: website
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
        - name: website
          image: website:prelive
          ports:
            - containerPort: 80
